//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_User
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public byte Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime Addtime { get; set; }
        public string Pwd { get; set; }
    }
}
